Support more GitHub events
prologin/prololo pull request #17
Opened 2022-01-02 19:12 UTC by Nhqml

Add support for more GitHub events. It is planned to support all missing events described in #1.

Also, note that I added support for "Ping" event. Kinda useless for general use but I believe it could be helpful for newcomers to know they've successfully setup prololo/matrix/webhooks instead of having an error.

2022-01-04 14:10 UTC, Nhqml commented
I will add some unit tests later (I'm lazy atm :eyes:) but otherwise it's ready for review.

2022-01-04 14:31 UTC, alarsyo requested changes
Looks great, thanks for finishing this! Small nits here and there.

About the deserialization error on `transferred`, I'll try to reproduce and investigate.

2022-01-04 14:31 UTC, alarsyo commented on src/bot/emoji.rs
> +pub(crate) const PEOPLE: char = '\u{1F9D1}';
Let's keep this alphabetically sorted

2022-01-04 14:31 UTC, alarsyo commented on src/bot/github.rs
> +    message.link(&commit_id[..SHORT_HASH_LENGTH], &commit_html_url);
deletion / edition of comments should probably be filtered, see [here](https://github.com/prologin/oldtools/blob/35f51656f71fb64218e657e8ebba53006774861f/ircbot/handlers/github.py#L332-L334)

2022-01-04 14:31 UTC, alarsyo commented on src/bot/github.rs
> +    };
How about something like

```rust
    let format_string = match action.as_str() {
        "added" => " {} added {} to team",
        "removed" => " {} removed {} from team",
        _ => {
            error!("invalid or unsupported membership action: {}", action);
            return None;
        }
    };

    write!(&mut message, format_string, event.sender.login, event.member.login).unwrap();
```

2022-01-04 14:31 UTC, alarsyo commented on src/bot/message_builder.rs
> +    }
Is that voluntarily unused?

2022-01-04 18:52 UTC, Nhqml commented on src/bot/message_builder.rs
> +    }
I was planning on using it but I didn't since it wasn't more "clear" with it. I just left it there because :shrug:

2022-01-04 18:57 UTC, Nhqml commented on src/bot/github.rs
> +    message.link(&commit_id[..SHORT_HASH_LENGTH], &commit_html_url);
According to [this](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-4), commit comments can only be "created" (that's why `CommitCommentEvent` does not have an `action` field).

2022-01-04 19:04 UTC, Nhqml commented on src/bot/github.rs
> +    };
I think that the format must be a string literal (at least it is what the compiler is yelling at me :eyes:).

Maybe something like this would be a bit fancier?
```rust
   let preposition = match action.as_str() {
        "added" => "to",
        "removed" => "from",
        _ => {
            error!("invalid or unsupported membership action: {}", action);
            return None;
        }
    };
  
    write!(
        &mut message,
        " {} {} {} {} the team",
        event.sender.login, action, event.member.login, preposition
    )
    .unwrap();
```

2022-01-05 14:51 UTC, alarsyo commented on src/bot/github.rs
> +    };
Ah forgot about that rule, sure that's better

2022-01-05 14:53 UTC, alarsyo approved these changes

2022-01-05 15:00 UTC, merged