webhooks: shorten PRs and issues' titles
prologin/prololo pull request #9
Opened 2021-09-24 18:22 UTC by Max1Truc

2021-09-24 18:23 UTC, Max1Truc commented
The shortener function is mixed in the event handling, maybe it should be somewhere else.

2021-09-24 20:34 UTC, alarsyo requested changes
Nitpick about Rust's Unicode handling

2021-09-24 20:34 UTC, alarsyo commented on src/webhooks/github/events.rs
> +        content.split_at(max_length).0.to_owned() + "…"
This [will panic](https://doc.rust-lang.org/std/primitive.str.html#method.split_at) if 72 is in the middle of a unicode codepoint, if we're going to allocate a new `String` anyway to concatenate the `…`, might as well use something like `content.chars().take(max_length).collect()`

2021-09-24 20:37 UTC, alarsyo commented
> The shortener function is mixed in the event handling, maybe it should be somewhere else.

How about something like `bot/utils.rs`? It's more related to bot/message functionality, although I've put some `Display` impls near their type declarations here.

Long term I'm picturing a `MessageBuilder` struct that'll provide helper functions for this and HTML formatting, but for now a `utils` mod is fine

2021-09-25 11:40 UTC, alarsyo requested changes
Some other place where text should be shortened (comment body):

https://github.com/prologin/prololo/blob/9e7a56a269c38be1ebc6e6c2b8d10796ef08b4fe/src/bot/github.rs#L136

2021-09-28 14:25 UTC, alarsyo approved these changes
LGTM!

2021-09-28 14:25 UTC, merged